apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.14.0 (fa706f2)
  creationTimestamp: null
  labels:
    io.kompose.service: appdynamics-collector
  name: appdynamics-collector
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: appdynamics-collector
    spec:
      containers:
      - image: jmsv888/hygieia-appdynamics-collector
        name: appdynamics-collector
        resources: {}
      restartPolicy: Always
status: {}
