apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.14.0 (fa706f2)
  creationTimestamp: null
  labels:
    io.kompose.service: chat-ops-collector
  name: chat-ops-collector
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: chat-ops-collector
    spec:
      containers:
      - image: jmsv888/hygieia-chat-ops-collector
        name: chat-ops-collector
        resources: {}
      restartPolicy: Always
status: {}
